ServerUri = "localhost"
Port = 8883
#  MQTT protocol version to use ("V311", "V310" or "V500")
MqttVersion = "V500"            
Username = "hivemq.webclient.1712151657543"
Password = "kpT6Rr91.lLQ4f<@aFJ%"
ConnectionTimeOut = 1
KeepAlivePeriod = 60
CleanSession = true
#  number of clients to use for the benchmark
ClientCount = 80
#  number of messages to send from each client
MessageCount = 5000
#  size of each message in bytes
MessageSize = 10
#  quality of service level to use for message delivery (0, 1 or 2)
Qos = 2                        
Retain = false
